name: A workflow for my Email Action file
on: push

jobs:
  build:
    name: Email action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./ActionDir
        with:
          EMAIL: "michael.harris@abbvie.com"
